### ISSUE TITLE
ModuleNotFoundError: No module named 'grit.data'  No module named 'centernet.data'` 

### ISSUE THREAD

**Issue by so-as** [YujieLu10/LLMScore#1]
Hi，thanks for your excellent work! 
When I ran the demo  `python llm_score.py`， I encountered some problems, such as `ModuleNotFoundError: No module named 'grit.data'` `ModuleNotFoundError: No module named 'centernet.data'`。  In submodule/CenterNet2/centernet directory，there is no data dir，same as submodule/grit dir. 
Did you miss submitting some code files?  how to fix this problem,  Looking forward to your  reply.

@YujieLu10

**Comment by YujieLu10** [comment]
Thank you for your interest in our work!
I directly add the full directory of submodule/CenterNet2/centernet/data and submodule/girt/data. The detectron2 will remain as a submodule.
Besides, I update the requirements.txt to support BLIP2 using huggingface. You may find it easier to re-install the environment following the new INSTALL.md
